//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public int Id { get; set; }
        public int OperationTypeId { get; set; }
        public string Name { get; set; }
        public decimal Value { get; set; }
        public System.DateTime OperationTime { get; set; }
    
        public virtual OperationType OperationType { get; set; }
    }
}
